export const styles = {
  input: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: "10px",
    border: "2px solid #e0e0e0",
    fontSize: "14px",
    outline: "none",
    boxSizing: "border-box",
    background: "#fff",
  },
  card: {
    background: "#fff",
    borderRadius: "16px",
    padding: "20px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
  },
  btnPrimary: {
    background: "linear-gradient(135deg, #2d6a4f, #40916c)",
    color: "#fff",
    border: "none",
    borderRadius: "10px",
    padding: "10px 20px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
  },
  btnSecondary: {
    background: "#f0f0f0",
    color: "#666",
    border: "none",
    borderRadius: "8px",
    padding: "8px 16px",
    cursor: "pointer",
    fontSize: "14px",
  },
  pageContainer: {
    maxWidth: "900px",
    margin: "0 auto",
    padding: "24px",
  },
  pageHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "16px",
  },
  pageTitle: {
    margin: 0,
    color: "#2d6a4f",
    fontSize: "20px",
  },
  emptyState: {
    textAlign: "center",
    padding: "48px 20px",
  },
  errorBox: {
    background: "#fff3f3",
    border: "1px solid #ffcccc",
    borderRadius: "16px",
    padding: "16px",
    marginBottom: "16px",
  },
};